/**
 * @addtogroup  aidl
 * @{
 * @file        tenSwUpdateError.aidl
 * @brief       defines interface for SWU service
 *
 * @copyright   (C) 2023 Robert Bosch GmbH.
 *              The reproduction, distribution and utilization of this file as
 *              well as the communication of its contents to others without express
 *              authorization is prohibited. Offenders will be held liable for the
 *              payment of damages. All rights reserved in the event of the grant
 *              of a patent, utility model or design.
 * @}
 */
 package swu.FcSwUpdateSrv;

enum tenSwUpdateError{
      ERROR_OK = 0,
      ERROR_DOWNLOAD_MRG_BUSY = 2,
      ERROR_ERG_WRITE = 3,
      ERROR_ERG_READ = 4,
      ERROR_NOT_ENOUGH_MEMORY = 5,
      ERROR_SUMMARY_SCREENS = 6,
      ERROR_INVALID_SOURCE_SET = 7,
      ERROR_UNKNOWN = 8,
      ERROR_METAINFO_NOT_FOUND = 9,
      ERROR_METAINFO_READ = 10,
      ERROR_METAINFO_CHECKSUM = 11,
      ERROR_METAINFO_PARSE = 12,
      ERROR_METAINFO_SECTION_COMMON_NOT_FOUND = 13,
      ERROR_METAINFO_SECTION_SIGNATURE_NOT_FOUND = 14,
      ERROR_METAINFO_MANDATORY_TAG_NOT_FOUND = 15,
      ERROR_METAINFO_DUPLICATE_SECTION = 16,
      ERROR_METAINFO_SECTION_NOT_FOUND = 17,
      ERROR_METAINFO_UNEXPECTED_SUBSECTION = 18,
      ERROR_METAINFO_INVALID_SUBSECTION_PATH = 19,
      ERROR_METAINFO_REGION_CONFLICT = 20,
      ERROR_METAINFO_VARIANT_CONFLICT = 21,
      ERROR_METAINFO_INVALID_TRAIN_NAME = 22,
      ERROR_IMAGE_SIZE = 23,
      ERROR_IMAGE_CHECKSUM = 24,
      ERROR_IMAGE_INVALID_SECTORHEADER = 25,
      ERROR_IMAGE_INCOMPATIBLE_VERSION = 26,
      ERROR_IMAGE_READ = 27,
      ERROR_IMAGE_FLASHING = 28,
      ERROR_IMAGE_DEVICE_NOT_SUPPORTED = 29,
      ERROR_IMAGE_DEVICE_NOT_READY = 30,
      ERROR_IMAGE_DEVICE_NOT_SELECTED = 31,
      ERROR_IMAGE_DEVICE_INCOMPATIBLE_DM_VERSION = 32,
      ERROR_SIGNATURE_CHECK_FAILED = 33,
      ERROR_NO_RELEASE_FOUND = 35,
      ERROR_MEDIA_UNAVAILABLE = 36,
      ERROR_MEDIUM_REMOVED = 37,
      ERROR_IMAGE_INCOMPATIBLE_DOWNGRADE = 39,
      ERROR_IMAGE_INCOMPATIBLE_SAME_VERSION = 40,
      ERROR_INCOMPATIBLE_USB_FORMAT = 42,
      ERROR_ACTIVATE_PENDING_NOT_READY = 43,
      ERROR_INCOMPATIBLE_IMAGE_NONDELTA = 44,
      ERROR_ACTIVATION_VERIFICATION_AFTER_REBOOT = 45,
      ERROR_IMAGE_INCOMPATIBLE_VERSION_FORMAT = 46,
      ERROR_SET_RECOVERYBCB_FAILED = 47,
      ERROR_SINGLE_BANK_UPDATE_FAILED = 48,
      ERROR_SUB_FIRMWARE_UPDATE_FAILED = 49,
      ERROR_REBOOT_TO_RECOVERY_FAILED = 50,
      ERROR_CANCEL_UPD_FAILURE = 51,
      ERROR_COMPLETE_UPD_FAILURE = 52,
      ERROR_CANCEL_BY_USER = 53,
      ERROR_CANCEL_HANDLING = 54,
      ERROR_ONGOING_UPDATE = 55,
      ERROR_ACTIVATION_CODE_VERIFICATION_FAILED = 56,
      ERROR_ROLLBACK_UPD_FAILURE = 57,
      ERROR_DUAL_BANK_ACTIVATE_FAILED = 58
  }